# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - learner-portal


pool:
  name: ufi-server

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  workingDirectory: 'learner-portal'
  displayName: 'yarn install'

- script: |
    yarn build
  workingDirectory: 'learner-portal'
  displayName: 'yarn build'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'   
    sourceFolder: '$(Build.SourcesDirectory)/learner-portal/build'
    contents: '**/*' 

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
