# Generated by Django 4.1.3 on 2023-02-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('target_site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tutorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='synapi.tutorial')),
            ],
            options={
                'ordering': ['tutorial_id', 'index'],
                'unique_together': {('tutorial_id', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.URLField()),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('tutorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='synapi.tutorial')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('action_type', models.CharField(choices=[('', 'Ng'), ('Left Click', 'Lc'), ('Right Click', 'Rc'), ('Left Double Click', 'Ldc'), ('Right Double Click', 'Rdc'), ('Enter', 'En')], default='', max_length=50)),
                ('action_target', models.CharField(blank=True, max_length=250)),
                ('action_content', models.CharField(blank=True, max_length=250)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='synapi.step')),
            ],
            options={
                'ordering': ['step_id', 'index'],
                'unique_together': {('step_id', 'index')},
            },
        ),
    ]
