# Generated by Django 4.1.3 on 2023-03-24 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('openai_response', models.JSONField()),
                ('error_message', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='synapi.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='synapi.tutorial')),
            ],
            options={
                'ordering': ['tutorial', 'index'],
                'unique_together': {('tutorial', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.URLField()),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('tutorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='synapi.tutorial')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('type', models.CharField(choices=[('None', 'Ng'), ('Left Click', 'Lc'), ('Right Click', 'Rc'), ('Left Double Click', 'Ldc'), ('Right Double Click', 'Rdc'), ('Enter', 'En'), ('Scroll Up', 'Su'), ('Scroll Down', 'Sd')], default='None', max_length=50)),
                ('target_element', models.CharField(blank=True, max_length=250)),
                ('extras', models.CharField(max_length=250, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='synapi.step')),
            ],
            options={
                'ordering': ['step_id', 'index'],
                'unique_together': {('step_id', 'index')},
            },
        ),
    ]
