# Generated by Django 4.1.3 on 2022-11-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('targetSite', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('tutorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='synapi.tutorial')),
            ],
            options={
                'ordering': ['tutorial_id', 'index'],
                'unique_together': {('index', 'tutorial_id')},
            },
        ),
        migrations.CreateModel(
            name='TutorialTextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('targetSelector', models.CharField(max_length=100)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textboxes', to='synapi.tutorialstep')),
            ],
        ),
    ]
