# Generated by Django 4.1.3 on 2022-12-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialtextbox',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='synapi.tutorialstep'),
        ),
    ]
