# Generated by Django 4.1.3 on 2023-03-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='extras',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
