# Generated by Django 4.1.3 on 2023-03-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0002_alter_action_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
