# Generated by Django 4.1.3 on 2022-12-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0002_alter_tutorialtextbox_step_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorialTextBox',
            new_name='Action',
        ),
    ]
