# Generated by Django 4.1.3 on 2022-12-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0003_rename_tutorialtextbox_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='title',
        ),
    ]
