# Generated by Django 4.1.3 on 2023-03-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0003_action_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='target_website',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
