# Generated by Django 4.1.3 on 2022-12-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0004_remove_action_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='targetSelector',
            new_name='target_elem',
        ),
    ]
