# Generated by Django 4.1.3 on 2022-12-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0005_rename_targetselector_action_target_elem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_elem',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
