# Generated by Django 4.1.3 on 2022-12-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0006_alter_action_target_elem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='targetSite',
            new_name='target_site',
        ),
    ]
