# Generated by Django 4.1.3 on 2022-12-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0007_rename_targetsite_tutorial_target_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='name',
            new_name='title',
        ),
    ]
