# Generated by Django 4.1.3 on 2022-12-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0010_tutorial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialstep',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
