# Generated by Django 4.1.3 on 2022-12-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0011_tutorialstep_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorialStep',
            new_name='Step',
        ),
    ]
