# Generated by Django 4.1.3 on 2022-12-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0012_rename_tutorialstep_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='mouse_action',
            field=models.CharField(choices=[('', 'None'), ('CLICK', 'Click'), ('DBCLICK', 'Double Click')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='action',
            name='mouse_button',
            field=models.CharField(choices=[('', 'None'), ('L', 'Left'), ('R', 'Right'), ('M', 'Middle')], default='', max_length=1),
        ),
    ]
