# Generated by Django 4.1.3 on 2022-12-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0013_action_mouse_action_action_mouse_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['step_id', 'index']},
        ),
        migrations.AddField(
            model_name='action',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('step_id', 'index')},
        ),
    ]
