# Generated by Django 4.1.3 on 2023-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0014_alter_action_options_action_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
