# Generated by Django 4.1.3 on 2023-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0015_alter_action_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='mouse_action',
        ),
        migrations.RemoveField(
            model_name='action',
            name='mouse_button',
        ),
        migrations.RemoveField(
            model_name='action',
            name='target_elem',
        ),
        migrations.AddField(
            model_name='action',
            name='action_content',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='action',
            name='action_target',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('', 'Ng'), ('Left Click', 'Lc'), ('Right Click', 'Rc'), ('Left Double Click', 'Ldc'), ('Right Double Click', 'Rdc'), ('Enter', 'En')], default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('tutorial_id', 'index')},
        ),
    ]
