# Generated by Django 4.1.3 on 2023-02-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synapi', '0016_remove_action_mouse_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.URLField()),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('tutorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='synapi.tutorial')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
